version: '3.8'

services:
  blackjack-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    privileged: true  
    devices:
      - "/dev/video0:/dev/video0"  
      - "/dev/video2:/dev/video2"  
